// One-time generator: converts us-atlas's pre-projected (Albers USA) states
// topology into a compact static JS module of SVG path strings + centroids,
// keyed by USPS postal abbreviation (matching the `st` field centers already
// carry). Run manually (`node scripts/gen-us-map.js`) whenever the source
// topology needs to change — the OUTPUT (src/usMapData.js) is what's
// actually imported/bundled; us-atlas/topojson-client are not runtime deps.
const fs = require("fs");
const path = require("path");
const topojson = require("topojson-client");
const us = require("us-atlas/states-albers-10m.json");

// FIPS -> USPS postal code, for every state/territory this network model
// actually has centers in (see MODEL_ST in src/Engine.tsx) plus DC.
const FIPS_TO_POSTAL = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO",
  "09": "CT", "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI",
  "16": "ID", "17": "IL", "18": "IN", "19": "IA", "20": "KS", "21": "KY",
  "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN",
  "28": "MS", "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
  "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND", "39": "OH",
  "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA",
  "54": "WV", "55": "WI", "56": "WY", "72": "PR",
};

function ringToPath(ring) {
  return "M" + ring.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join("L") + "Z";
}

// Shoelace-based centroid (area-weighted), correct for simple polygons —
// good enough for label/dot placement, not used for anything geometric.
function polygonCentroid(ring) {
  let a = 0, cx = 0, cy = 0;
  for (let i = 0; i < ring.length - 1; i++) {
    const [x0, y0] = ring[i], [x1, y1] = ring[i + 1];
    const cross = x0 * y1 - x1 * y0;
    a += cross; cx += (x0 + x1) * cross; cy += (y0 + y1) * cross;
  }
  a *= 0.5;
  if (Math.abs(a) < 1e-9) {
    const xs = ring.map(p => p[0]), ys = ring.map(p => p[1]);
    return [(Math.min(...xs) + Math.max(...xs)) / 2, (Math.min(...ys) + Math.max(...ys)) / 2];
  }
  return [cx / (6 * a), cy / (6 * a)];
}

const geo = topojson.feature(us, us.objects.states);
const paths = {};
const centroids = {};

geo.features.forEach(f => {
  const postal = FIPS_TO_POSTAL[f.id];
  if (!postal) return; // territory this model doesn't carry (e.g. AS, GU, MP, VI)
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  // Combine every ring (outer + inner holes, and every polygon of a
  // MultiPolygon like MI/HI/etc.) into one path string via multiple M..Z
  // subpaths — SVG fill-rule handles holes/islands correctly this way.
  const d = polys.map(poly => poly.map(ringToPath).join("")).join("");
  paths[postal] = d;
  // Centroid from the largest ring by point count (proxy for largest island/
  // landmass) so multi-polygon states (MI, HI) label on their main body.
  const allRings = polys.flat();
  const biggest = allRings.reduce((a, b) => (b.length > a.length ? b : a));
  const [cx, cy] = polygonCentroid(biggest);
  centroids[postal] = [+cx.toFixed(1), +cy.toFixed(1)];
});

console.log("Generated", Object.keys(paths).length, "state paths");
console.log("bbox", us.bbox);

const out = `// GENERATED by scripts/gen-us-map.js — do not hand-edit.
// Real US state boundaries, Albers-USA projected (viewBox 0 0 975 610),
// derived from us-atlas (public-domain US Census TIGER/Line data via
// topojson). Canadian provinces (BC/AB/ON) this network also models have
// no coordinates here — Albers USA doesn't define space for Canada — and
// are positioned separately as approximate pins in usMapCanadaPins.
export const US_MAP_VIEWBOX = "0 0 975 610";
export const US_STATE_PATHS = ${JSON.stringify(paths)};
export const US_STATE_CENTROIDS = ${JSON.stringify(centroids)};
// Hand-placed approximate pins for the three Canadian provinces this model
// carries centers in, positioned just outside the Albers USA frame in their
// real relative direction (BC: west/north of WA, AB: north of MT, ON: north
// of the Great Lakes/NY) — not a projection, just a legible callout position.
export const US_MAP_CANADA_PINS = {
  BC: [55, 30], AB: [175, 20], ON: [660, 15],
};
`;
fs.writeFileSync(path.join(__dirname, "..", "src", "usMapData.js"), out);
console.log("Wrote src/usMapData.js,", out.length, "bytes");
